### ISSUE TITLE
[Bug]: `prefers-color-scheme: dark` breaks UI colors

### ISSUE THREAD

**Issue by emersion** [SchweizerischeBundesbahnen/netzgrafik-editor-frontend#156]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/SchweizerischeBundesbahnen/netzgrafik-editor-frontend/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/SchweizerischeBundesbahnen/netzgrafik-editor-frontend/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/orgs/sbb-design-systems/projects/1) for an issue that matches the one I want to file, without success.

### Bug type

Functionality

### Operating system

Linux

### Browser / Browser version

Firefox

### Input mode

None

### What happened?

When the browser is configured to prefer dark themes, the UI colors are messed up (see screenshot below). Sidebars are black, icons have the same color as the background, etc.

It seems part of the styles have some [`prefers-color-scheme`](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme) CSS rules, and part of the styles don't.

![out](https://github.com/SchweizerischeBundesbahnen/netzgrafik-editor-frontend/assets/506932/fdfc4e68-7a39-4ccc-a645-010b93fcf644)

### Steps to reproduce the issue

1. Go to Firefox settings
2. Go to General → Language and Appearance → Website appearance
3. Select "Dark"
4. Load NGE

**Comment by louisgreiner** [comment]
duplicate #62
