### ISSUE TITLE
[Feature request]: Publish a demo

### ISSUE THREAD

**Issue by emersion** [SchweizerischeBundesbahnen/netzgrafik-editor-frontend#218]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/SchweizerischeBundesbahnen/netzgrafik-editor-frontend/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/SchweizerischeBundesbahnen/netzgrafik-editor-frontend/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/orgs/sbb-design-systems/projects/1) for an issue that matches the one I want to file, without success.

### Request type

Request for a new component

### Functionality

It would be super nice if there was a demo of NGE hosted somewhere so that people can play with it and see what NGE can do.

Simplest approach would be to host the standalone version on GitHub Pages.

**Comment by emersion** [comment]
Aha, let me know if you need any help!

**Comment by aiAdrian** [comment]
The demo is ready: [nge.flatland.cloud](https://nge.flatland.cloud/)

**Comment by aiAdrian** [comment]
The demo is ready: [nge.flatland.cloud](https://nge.flatland.cloud/)

**Comment by emersion** [comment]
Excellent, thanks a bunch!
