### ISSUE TITLE
[Bug]: NGE Flatland doens't handle expired tokens

### ISSUE THREAD

**Issue by louisgreiner** [SchweizerischeBundesbahnen/netzgrafik-editor-frontend#284]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/SchweizerischeBundesbahnen/netzgrafik-editor-frontend/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/SchweizerischeBundesbahnen/netzgrafik-editor-frontend/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/orgs/sbb-design-systems/projects/1) for an issue that matches the one I want to file, without success.

### Bug type

Accessibility

### Which version are you using

2.7.13

### Operating system

Windows 11

### Browser / Browser version

Mozilla 115

### Input mode

Mouse/Keyboard

### What happened?

![image](https://github.com/user-attachments/assets/d978ed0b-88ba-4672-abe8-d996a4ea3b83)

Seems like expired tokens are not handled (I signed in with GitHub)

### Steps to reproduce the issue

1. wait long enough for tokens to expire?

**Comment by aiAdrian** [comment]
Task: @louisgreiner

Please retest. I am not sure if the issue still exists. I currently cannot reproduce the problem on my end.

**Comment by louisgreiner** [comment]
After testing and playing with the tokens stored, I can't reproduce neither :/ I guess we can close this issue
