### ISSUE TITLE
[Translation issues]: What are the best translations

### ISSUE THREAD

**Issue by louisgreiner** [SchweizerischeBundesbahnen/netzgrafik-editor-frontend#291]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/SchweizerischeBundesbahnen/netzgrafik-editor-frontend/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/SchweizerischeBundesbahnen/netzgrafik-editor-frontend/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/orgs/sbb-design-systems/projects/1) for an issue that matches the one I want to file, without success.

## Open discussion

Choices have to be made about a few business words:
- "Trainrun" (EN) -> "Ligne de train" (FR) or "Trajet de train" (FR) ou "Course de train" (FR) ? As NGE uses also "Trainrun" (EN), even for the German version. Also, "Zugfahrt" (DE) doesn't exactly mean "Trainrun" (EN) right ?
- "Netzgrafik" (DE) -> "Réticulaire" (FR) or "Graphique de réseau" (FR) ? (At SNCF, we mostly use "Réticulaire" (FR), https://www.sncf-reseau.com/medias-publics/2023-11/R%C3%A9ticulaire%20PER%20Marseille-Vintimille%20SA%202025%20-%2030%20Novembre%202023.pdf)
- "Label" (DE/EN) -> "Label" (FR) or "Etiquette" (FR) ?

**Comment by aiAdrian** [comment]
In my personal opinion the following translation would be fine:
- Trainrun -> Trajet de train (FR) 
  The german Zugfahrt is fine.
- Netzgrafik (DE) -> Réticulaire (FR)  or  graphique réticulaire (FR)
- Label -> Label (FR)

**Comment by louisgreiner** [comment]
It's noted, thanks, I'll update this asap
