### ISSUE TITLE
[Bug]: Origin/Destination Matrix - not all path are reported/found

### ISSUE THREAD

**Issue by aiAdrian** [SchweizerischeBundesbahnen/netzgrafik-editor-frontend#312]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/SchweizerischeBundesbahnen/netzgrafik-editor-frontend/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/SchweizerischeBundesbahnen/netzgrafik-editor-frontend/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/orgs/sbb-design-systems/projects/1) for an issue that matches the one I want to file, without success.

### Bug type

Functionality

### Which version are you using

2.8.0

### Operating system

Windows 10

### Browser / Browser version

Google Chrome

### Input mode

None

### What happened?

The Origin-Destination Matrix is not finding all connections, i.e., routes. For example, no route is found for Bern - Biel; consequently, the entry is blank in the CSV export.

Test: https://schweizerischebundesbahnen.github.io/netzgrafik-editor-frontend/

<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/u216993/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/u216993/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/u216993/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/u216993/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

</body>

</html>

Origin | Destination | Travel time | Connections | Total cost
-- | -- | -- | -- | --
...| ...|  ... |...   |  
Bern | Biasca | 195 | 2 | 205
Bern | Biel |   |   |  
Bern | BNWD |   |   |  
...| ...|  ... |...   |  

</body>

</html>

![image](https://github.com/user-attachments/assets/a0612e1a-3999-4f28-a9e0-28721abb86f5)
The matrix shows all connection durations (if not available or = 0 => no coloring) and the number of transfers are given as text (numbers).

### Steps to reproduce the issue

1. Open https://schweizerischebundesbahnen.github.io/netzgrafik-editor-frontend/
2. Navigate to the left menu bar, select More functions -> Netzgrafik -> Origin-Destination as CSV.
3. Open the exported CSV file and search for Bern -> Biel.

### Relevant log output

Attempting initialization Mon Oct 14 2024 16:03:40 GMT+0200 (Mitteleuropäische Sommerzeit)
origin-destination-graph.ts:142 Ignoring trainrun (no root found):  85
origin-destination-graph.ts:142 Ignoring trainrun (no root found):  86
origin-destination-graph.ts:142 Ignoring trainrun (no root found):  87
origin-destination-graph.ts:142 Ignoring trainrun (no root found):  88
origin-destination-graph.ts:142 Ignoring trainrun (no root found):  89
origin-destination-graph.ts:142 Ignoring trainrun (no root found):  90

```
const buildSectionEdges = (trainruns: Trainrun[], trainrunService: TrainrunService, timeLimit: number): Edge[] => {
    const edges = [];
    const its = trainrunService.getRootIterators();
    trainruns.forEach((trainrun) => {
        const tsIterators = its.get(trainrun.getId());
        if (tsIterators === undefined) {
          console.log("Ignoring trainrun (no root found): ", trainrun.getId());
          return;
        }
        tsIterators.forEach((tsIterator) => {
          edges.push(...buildSectionEdgesFromIterator(tsIterator, false, timeLimit));
          const ts = tsIterator.current().trainrunSection;
          const nextIterator = trainrunService.getIterator(ts.getTargetNode(), ts);
          edges.push(...buildSectionEdgesFromIterator(nextIterator, true, timeLimit));
        });
    });
    return edges;
};
```

**Comment by louisgreiner** [comment]
@shenriotpro I think it is related to the fact that trainruns can have no `EndNode` (without root)

**Comment by shenriotpro** [comment]
I see two issues with this example:

1. The assumption is that trainruns are one or several (caveat https://github.com/SchweizerischeBundesbahnen/netzgrafik-editor-frontend/issues/285) linked lists, this is not the case here, e.g. with trainrun 85. Iterators make the same assumption, right?
![image](https://github.com/user-attachments/assets/f47e0625-6a34-412c-926b-f821167ef154)
2. On the same trainrun 85, the node 135 is not considered an endNode because the two trainrunSections have ports 1149 et 1401, and there is a transition between those ports. https://github.com/SchweizerischeBundesbahnen/netzgrafik-editor-frontend/blob/d67445abbc7ff57767229a46a6a61f0f05ba41ec/src/app/models/node.model.ts#L417

**Comment by shenriotpro** [comment]
Let's keep in mind that performance may become worse after these issues are fixed.

**Comment by aiAdrian** [comment]
[originDestination (10).csv](https://github.com/user-attachments/files/17456658/originDestination.10.csv)
[netzgrafik_version_1.json](https://github.com/user-attachments/files/17456663/netzgrafik_version_1.json)
![image](https://github.com/user-attachments/assets/73dd4853-247c-4648-9f9f-c8397e8f114b)
![image](https://github.com/user-attachments/assets/74e6d0f6-8932-4069-818f-2f134f8d7b1c)

BN - LZ doesn't have a connection => See plotted matrix

**Comment by shenriotpro** [comment]
It's a similar issue, the trainrun 4 is ignored because it's ordered ZG -> LZ and ZG -> GD (nonlinear).
Perhaps trainruns should be re-ordered like the trainrun view displays them.

**Comment by shenriotpro** [comment]
This view (perlenkette) relies more heavily on iterators. On the one hand, it's nice that iterators are resilient for routing, on the other hand consecutiveTime looks wrong in these cases (similar to https://github.com/SchweizerischeBundesbahnen/netzgrafik-editor-frontend/issues/285).

```
        {
            "id": 9,
            "path": ...,
            "warnings": null,
            "resourceId": 0,
            "trainrunId": 4,
            "travelTime": {
                "lock": true,
                "time": 1,
                "warning": null,
                "timeFormatter": null,
                "consecutiveTime": 1
            },
            "sourceNodeId": 5,
            "sourcePortId": 17,
            "targetNodeId": 10,
            "targetPortId": 18,
            "numberOfStops": 0,
            "sourceArrival": {
                "lock": false,
                "time": 0,
                "warning": null,
                "timeFormatter": null,
                "consecutiveTime": 120
            },
            "targetArrival": {
                "lock": false,
                "time": 1,
                "warning": null,
                "timeFormatter": null,
                "consecutiveTime": 61
            },
            "sourceDeparture": {
                "lock": false,
                "time": 0,
                "warning": null,
                "timeFormatter": null,
                "consecutiveTime": 60
            },
            "targetDeparture": {
                "lock": false,
                "time": 59,
                "warning": null,
                "timeFormatter": null,
                "consecutiveTime": 119
            },
            "specificTrainrunSectionFrequencyId": null
        },
        {
            "id": 10,
            "path":...,
            "warnings": null,
            "resourceId": 0,
            "trainrunId": 4,
            "travelTime": {
                "lock": true,
                "time": 1,
                "warning": null,
                "timeFormatter": null,
                "consecutiveTime": 1
            },
            "sourceNodeId": 5,
            "sourcePortId": 26,
            "targetNodeId": 3,
            "targetPortId": 20,
            "numberOfStops": 0,
            "sourceArrival": {
                "lock": false,
                "time": 57,
                "warning": null,
                "timeFormatter": null,
                "consecutiveTime": 57
            },
            "targetArrival": {
                "lock": false,
                "time": 4,
                "warning": null,
                "timeFormatter": null,
                "consecutiveTime": 124
            },
            "sourceDeparture": {
                "lock": false,
                "time": 3,
                "warning": null,
                "timeFormatter": null,
                "consecutiveTime": 123
            },
            "targetDeparture": {
                "lock": false,
                "time": 56,
                "warning": null,
                "timeFormatter": null,
                "consecutiveTime": 56
            },
            "specificTrainrunSectionFrequencyId": null
        },
```

It feels like there are a few discrepencies between the trainrun/trainrunSection models, the iterators, the way endNodes are checked, and the way consecutiveTimes are computed.

**Comment by aiAdrian** [comment]
To understand how traversing the trainrun works, please also take a look at this page: 

![image](https://github.com/user-attachments/assets/caaf04f5-8cc4-432f-8984-7e19e70126f7)

https://github.com/SchweizerischeBundesbahnen/netzgrafik-editor-frontend/blob/main/documentation/DATA_MODEL.md#data-model

**Comment by shenriotpro** [comment]
important bit from @aiAdrian : "important is to understand that the section (src, target) can be in any direction and the don't have any connections inbeetween section - means that there is no src > target > src > target order givent"

**Comment by shenriotpro** [comment]
possibly another issue: currently the O/D graph assumes all trainruns start at the same time offset (say 0)

**Comment by shenriotpro** [comment]
possibly another issue: currently the O/D graph does not consider connections within the same trainrun ID, but that might be useful if a trainrun goes several times through the same node

**Comment by shenriotpro** [comment]
Here is a plan to fix most issues (entrypoint buildSectionEdges https://github.com/SchweizerischeBundesbahnen/netzgrafik-editor-frontend/blob/d170955ecc466bfa9c10071927c63199eb7a86f7/src/app/view/util/origin-destination-graph.ts#L215):

0. we should update tests
1. getRootIterators should check for Targets as well (similar to getBothEndNodesWithTrainrunId) https://github.com/SchweizerischeBundesbahnen/netzgrafik-editor-frontend/blob/main/src/app/services/data/trainrun.service.ts#L781 and probably pick the smallest consecutiveTime. Supporting split trainruns is not useful.
2. in buildSectionEdgesFromIterator, reverse should only be used for the trainrunId, the other checks should compare the source node and the iterator
