### ISSUE TITLE
[Bug]: consecutiveTime is misleading for unordered trainruns

### ISSUE THREAD

**Issue by shenriotpro** [SchweizerischeBundesbahnen/netzgrafik-editor-frontend#319]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/SchweizerischeBundesbahnen/netzgrafik-editor-frontend/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/SchweizerischeBundesbahnen/netzgrafik-editor-frontend/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/orgs/sbb-design-systems/projects/1) for an issue that matches the one I want to file, without success.

### Bug type

Functionality

### Which version are you using

2.8.0

### Input mode

None

### What happened?

Describe in detail the issue you are having.
What did you expect to happen? What happened instead? What would you like to see changed?
Is the issue related to a specific component?

### Steps to reproduce the issue

1. Trace a first trainrun section
2. Trace a second trainrun section, from the same source node
3. Export the JSON and look at consecutiveTimes

### Relevant log output

```shell
"trainrunSections": [
        {
            "id": 1,
            "sourceNodeId": 7,
            "sourcePortId": 1,
            "targetNodeId": 1,
            "targetPortId": 2,
            "travelTime": {
                "time": 1,
                "consecutiveTime": 1,
                "lock": true,
                "warning": null,
                "timeFormatter": null
            },
            "sourceDeparture": {
                "time": 0,
                "consecutiveTime": 60,
                "lock": false,
                "warning": null,
                "timeFormatter": null
            },
            "sourceArrival": {
                "time": 0,
                "consecutiveTime": 120,
                "lock": false,
                "warning": null,
                "timeFormatter": null
            },
            "targetDeparture": {
                "time": 59,
                "consecutiveTime": 119,
                "lock": false,
                "warning": null,
                "timeFormatter": null
            },
            "targetArrival": {
                "time": 1,
                "consecutiveTime": 61,
                "lock": false,
                "warning": null,
                "timeFormatter": null
            },
            "numberOfStops": 0,
            "trainrunId": 1,
            "resourceId": 0,
            "specificTrainrunSectionFrequencyId": null,
            "path": ...,
            "warnings": null
        },
        {
            "id": 2,
            "sourceNodeId": 7,
            "sourcePortId": 3,
            "targetNodeId": 8,
            "targetPortId": 4,
            "travelTime": {
                "time": 1,
                "consecutiveTime": 1,
                "lock": true,
                "warning": null,
                "timeFormatter": null
            },
            "sourceDeparture": {
                "time": 2,
                "consecutiveTime": 122,
                "lock": false,
                "warning": null,
                "timeFormatter": null
            },
            "sourceArrival": {
                "time": 58,
                "consecutiveTime": 58,
                "lock": false,
                "warning": null,
                "timeFormatter": null
            },
            "targetDeparture": {
                "time": 57,
                "consecutiveTime": 57,
                "lock": false,
                "warning": null,
                "timeFormatter": null
            },
            "targetArrival": {
                "time": 3,
                "consecutiveTime": 123,
                "lock": false,
                "warning": null,
                "timeFormatter": null
            },
            "numberOfStops": 0,
            "trainrunId": 1,
            "resourceId": 0,
            "specificTrainrunSectionFrequencyId": null,
            "path": ...,
            "warnings": null
        }
    ],
```

**Comment by shenriotpro** [comment]
related: https://github.com/SchweizerischeBundesbahnen/netzgrafik-editor-frontend/issues/285 and https://github.com/SchweizerischeBundesbahnen/netzgrafik-editor-frontend/issues/312

**Comment by aiAdrian** [comment]
To understand how traversing the trainrun works, please also take a look at this figure:

<img src="https://private-user-images.githubusercontent.com/10423646/378864886-caaf04f5-8cc4-432f-8984-7e19e70126f7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2Njc2MTIsIm5iZiI6MTcyOTY2NzMxMiwicGF0aCI6Ii8xMDQyMzY0Ni8zNzg4NjQ4ODYtY2FhZjA0ZjUtOGNjNC00MzJmLTg5ODQtN2UxOWU3MDEyNmY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIzVDA3MDgzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdiOTI0MzlmNDA0MzUxZGYzYWI1OTZhMDM4MzlmMDViMmQzMTJiZGM0ODk3YzYxMmUxMmQ0YWI3YTM4MTU3ZjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.qJJaCKpArNw6MgkoeuQE9RFL-fbJnWjqQ6ksDrLWNzA" alt="image" style="max-width: 100%;">

More information can be found at https://github.com/SchweizerischeBundesbahnen/netzgrafik-editor-frontend/blob/main/documentation/DATA_MODEL.md#data-model

The [TrainrunIterator](https://github.com/SchweizerischeBundesbahnen/netzgrafik-editor-frontend/blob/d170955ecc466bfa9c10071927c63199eb7a86f7/src/app/services/util/trainrun.iterator.ts#L12) 

TrainrunIterator operates over a structure that can be conceptualized as an undirected acyclic graph (DAG), where each train run is a connected component.

Structure:

- TrainrunSection: Each section has a source and a target node, analogous to an edge in a graph.
- Node: Nodes manage connections through ports, effectively acting as junction points within the graph.
- Transition: Transitions are internal connections within nodes, linking two train run sections through ports.

Traversal:
- Start from a given node ID and traverse through connected sections.
- Use the source and target nodes of each section to determine the path.
- When reaching a transition, continue traversing through the next connected section.
- Stop when no further transitions are available.


The TrainrunIterator can effectively traverse through the train run sections by leveraging the source and target nodes of each section. This approach removes the need to explicitly define a direction and uses the inherent structure of the train run sections and nodes to guide the traversal. By managing transitions within nodes and ensuring each section is visited once, the iterator can navigate through the entire train run efficiently.

**Comment by aiAdrian** [comment]
# TrainrunIterator

The TrainrunIterator is a concept aimed at iterating through the sections of a train run, similar to how one navigates through the edges of a graph. Here is a detailed description of how this iterator works and how it can be used:

## Structure of the Train Run
- **TrainrunSection**: Each section has a source node and a target node, connected by ports. These sections function similarly to edges in a graph.
- **Node**: Nodes manage the ports and serve as connection points within the graph.
- **Transition**: Transitions are internal connections within a node that link two trainrun sections through ports.
- **Graph**: The entire graph is generally an undirected acyclic graph (DAG). Each train run (segment) represents a connected component.

## Traversal Logic
- **Starting Point**: Iteration begins with a given node ID and a specific train run section.
- **Section Connection**: The iterator moves through connected sections by utilizing the source and target nodes of each section.
- **Transitions**: When a transition is reached, the next connected section is followed through the corresponding port.
- **End of Traversal**: Iteration ends when no further sections or transitions are available.

## Example Application
- **Initialization**: The iterator is initialized with a start node ID and a specific train run section.
- **Forward Traversal**: The iterator moves from section to section by navigating from one node to the next. During traversal, the source and target nodes of the sections are used to determine the path.
- **Backward Traversal**: To traverse in the opposite direction, the iterator can be re-initialized with the end node ID of the current traversal and the corresponding train run section. This reverses the path and allows a return to the starting point.

## Detailed Steps
1. **Start with a Node ID and a Trainrun Section**: The iterator begins with a defined node ID and a specific train run section. This represents the starting point.
2. **Section-wise Traversal**: The iterator traverses the sections by using the connections between the nodes. It moves from the source node to the target node of a section.
3. **Handling Transitions**: When a transition within a node is reached, the iterator follows the transition to the next connected section.
4. **Traversal End**: Iteration ends when no further connected sections or transitions are available. This signals the end of the train run.

## Summary
The TrainrunIterator enables structured traversal through the sections of a train run by using both a node ID and a specific train run section as a starting point. This increases the precision and flexibility of the traversal. By utilizing the source and target nodes of each section and following transitions within the nodes, the iterator can efficiently navigate through the entire train run. This method is particularly useful for traversing complex train run paths and ensuring that the traversal logic is correctly understood and applied both forwards and backwards.

If functionality should be initiated by providing a port ID, this could be a further extension allowing a start directly from a specific port. However, this functionality is not yet implemented.

**Comment by shenriotpro** [comment]
Closing this since I had misunderstood consecutiveTime: it makes sense to start from 57 here.
