### ISSUE TITLE
[Bug]: Combining a trainrun with one that has two trainrun parts causes getId() - error (undefined).

### ISSUE THREAD

**Issue by aiAdrian** [SchweizerischeBundesbahnen/netzgrafik-editor-frontend#330]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/SchweizerischeBundesbahnen/netzgrafik-editor-frontend/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/SchweizerischeBundesbahnen/netzgrafik-editor-frontend/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/orgs/sbb-design-systems/projects/1) for an issue that matches the one I want to file, without success.

### Bug type

Functionality

### Which version are you using

2.9.1

### Operating system

all

### Browser / Browser version

all 

### Input mode

None

### What happened?

Combining a trainrun with one that has two trainrun parts causes getId().

When the user combines a trainrun with another trainrun having two trainrun parts, the trainrun gets connected to the trainrun part which is directly connected. Then the second trainrun gets deleted. If there are other trainrun parts (trainrun sections), then the next time the user reloads/opens the Netzgrafik, the system causes an undefined error (getId()).

The problem is that all trainrun sections need to be reassigned to the first trainrun from which the trainrun gets combined.

### Steps to reproduce the issue

1. Import JSON (Netzgrafik)  [BUG.json](https://github.com/user-attachments/files/17616852/BUG.json)
2. Navigate to Sursee 
3. Select the Cargo Trainrun G 001
4. Press ctrl and drag the Cargo Trainrun G 001 trainrun section "pin" at Sursee and drop it onto the IC 002 trainrun trainrun section "Pin" at Sursee 
5. Reload -> error getId() 

In the JSON you can see that there is with Id 98 is deleted but still in use within some trainrun sections -> search for 
```
"trainrunId": 98,
```

**Comment by louisgreiner** [comment]
Tested and looks good to me 👍
