### ISSUE TITLE
[Bug]: Origin / Destination naming "connections"

### ISSUE THREAD

**Issue by munterfi** [SchweizerischeBundesbahnen/netzgrafik-editor-frontend#360]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/SchweizerischeBundesbahnen/netzgrafik-editor-frontend/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/SchweizerischeBundesbahnen/netzgrafik-editor-frontend/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/orgs/sbb-design-systems/projects/1) for an issue that matches the one I want to file, without success.

### Bug type

Functionality

### Which version are you using

2.9.9

### Operating system

all

### Browser / Browser version

all

### Input mode

None

### What happened?

I played with the great new feature: *Export origin-destination as CSV*

Example:

```csv
Origin;Destination;Travel time;Connections;Total cost
Aarau;Altdorf;97;1;102
Aarau;Arth-G.;74;1;79
Aarau;Baden;58;1;63
Aarau;Basel;61;1;66
Aarau;Bellinz.;131;1;136
...
```

The column **Connections** appears to represent the number of transfers / changes between public transport legs in a journey between two nodes / stops. Since in the Netzgrafik-Editor the term connection is already used for a different [concept](https://github.com/SchweizerischeBundesbahnen/netzgrafik-editor-frontend/blob/main/documentation/CREATE_CONNECTIONS.md.), perhaps consider renaming the column to **Transfers** or **Changes** to avoid confusion?

### Steps to reproduce the issue

1. Step one
2. Step two
3. ...

**Comment by aiAdrian** [comment]
Umsteigen (DE) / Changement (FR) / Transfer (EN) / Cambiamenti (IT)

**Comment by aiAdrian** [comment]
>> https://github.com/SchweizerischeBundesbahnen/netzgrafik-editor-frontend/blob/main/documentation/ORIGIN_DESTINATION_MATRIX.md

**Comment by louisgreiner** [comment]
Thanks for the remark, we miss-used the words a bit there, I'll fix it asap, based on Adrian proposals

> Umsteigen (DE) / Changement (FR) / Transfer (EN) / Cambiamenti (IT)
